[package]
name = "dam4nes"
version = "0.1.0"
authors = ["Robert Kalmar <rkalmar@cloudera.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
log = "0.4.11"
simplelog = "0.8.0"
sdl2 = "0.34.2"